PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?item ?matchedTerm ?matchKind
WHERE {
  {
    VALUES ?matchedTerm {

    }
    ?item rdfs:label ?matchedTerm .
    BIND("label" AS ?matchKind)
  }
  UNION
  {
    VALUES ?matchedTerm {

    }
    ?item skos:altLabel ?matchedTerm .
    BIND("alias" AS ?matchKind)
  }
}
ORDER BY ?item ?matchedTerm ?matchKind
