PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?item ?matchedTerm ?matchKind
WHERE {
  {
    VALUES ?matchedTerm {
    "Lien Son"@en
    "Liên Sơn"@en
    "Vu Ban"@en
    "Vụ Bản"@en
    "Xa Lien Son"@en
    "Xa Vu Ban"@en
    "Xã Liên Sơn"@en
    "Xã Vụ Bản"@en
    "Lien Son"@vi
    "Liên Sơn"@vi
    "Vu Ban"@vi
    "Vụ Bản"@vi
    "Xa Lien Son"@vi
    "Xa Vu Ban"@vi
    "Xã Liên Sơn"@vi
    "Xã Vụ Bản"@vi
    }
    ?item rdfs:label ?matchedTerm .
    BIND("label" AS ?matchKind)
  }
  UNION
  {
    VALUES ?matchedTerm {
    "Lien Son"@en
    "Liên Sơn"@en
    "Vu Ban"@en
    "Vụ Bản"@en
    "Xa Lien Son"@en
    "Xa Vu Ban"@en
    "Xã Liên Sơn"@en
    "Xã Vụ Bản"@en
    "Lien Son"@vi
    "Liên Sơn"@vi
    "Vu Ban"@vi
    "Vụ Bản"@vi
    "Xa Lien Son"@vi
    "Xa Vu Ban"@vi
    "Xã Liên Sơn"@vi
    "Xã Vụ Bản"@vi
    }
    ?item skos:altLabel ?matchedTerm .
    BIND("alias" AS ?matchKind)
  }
}
ORDER BY ?item ?matchedTerm ?matchKind
