PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?item ?matchedTerm ?matchKind
WHERE {
  {
    VALUES ?matchedTerm {
    "A Sao"@en
    "A Sào"@en
    "An Chau"@en
    "An Châu"@en
    "An Khanh"@en
    "An Khánh"@en
    "An Phong"@en
    "An Quang"@en
    "Bac Dong Hung"@en
    "Bac Dong Quan"@en
    "Bac Thai Ninh"@en
    "Bac Thuy Anh"@en
    "Bac Tien Hung"@en
    "Ben Hai"@en
    "Bich Hao"@en
    "Binh Minh"@en
    "Binh Son"@en
    "Bình Minh"@en
    "Bình Sơn"@en
    "Bích Hào"@en
    "Bắc Thái Ninh"@en
    "Bắc Thụy Anh"@en
    "Bắc Tiên Hưng"@en
    "Bắc Đông Hưng"@en
    "Bắc Đông Quan"@en
    "Bến Hải"@en
    "Cam Pha"@en
    "Cat Ngan"@en
    "Chau Ninh"@en
    "Chi Minh"@en
    "Chu Van An"@en
    "Chu Văn An"@en
    "Châu Ninh"@en
    "Chí Minh"@en
    "Con Tien"@en
    "Cát Ngạn"@en
    "Cẩm Phả"@en
    "Cồn Tiên"@en
    "Dak Song"@en
    "Dan Dien"@en
    "Dong Bang"@en
    "Dong Chau"@en
    "Dong Ha"@en
    "Dong Hai"@en
    "Dong Loc"@en
    "Dong Thai Ninh"@en
    "Dong Thanh"@en
    "Dong Thinh"@en
    "Dong Thuy Anh"@en
    "Dong Tien Hai"@en
    "Dong Tien Hung"@en
    "Duc Chau"@en
    "Duc Lap"@en
    "Duc Minh"@en
    "Duong An"@en
    "Duong Kinh"@en
    "Duy Tien"@en
    "Duy Tiên"@en
    "Dương Kinh"@en
    "Giao Binh"@en
    "Giao Bình"@en
    "Giao Minh"@en
    "Giao Ninh"@en
    "Giao Thuy"@en
    "Giao Thuỷ"@en
    "Hai Hau"@en
    "Hai Hung"@en
    "Hai Lang"@en
    "Hai Loc"@en
    "Hai Thinh"@en
    "Hoa Lac"@en
    "Hong Chau"@en
    "Hong Phong"@en
    "Hung Dao"@en
    "Hòa Lạc"@en
    "Hưng Đạo"@en
    "Hải Hưng"@en
    "Hải Hậu"@en
    "Hải Lăng"@en
    "Hải Lộc"@en
    "Hải Thịnh"@en
    "Hồng Châu"@en
    "Hồng Phong"@en
    "Kim Anh"@en
    "Kim Bang"@en
    "Kim Bảng"@en
    "Kim Son"@en
    "Kim Sơn"@en
    "Ky Anh"@en
    "Ky Lua"@en
    "Kỳ Anh"@en
    "Kỳ Lừa"@en
    "Lam Thanh"@en
    "Lam Thành"@en
    "Le Dai Hanh"@en
    "Le Ich Moc"@en
    "Lien Son Lak"@en
    "Liên Sơn Lắk"@en
    "Luong Son"@en
    "Lê Ích Mộc"@en
    "Lê Đại Hành"@en
    "Lương Sơn"@en
    "Mai Son"@en
    "Mai Sơn"@en
    "Mau Thach"@en
    "Minh Thai"@en
    "Minh Thái"@en
    "Muong Ham"@en
    "Muong La"@en
    "Muong Quang"@en
    "My Duc"@en
    "My Hao"@en
    "Mường Ham"@en
    "Mường La"@en
    "Mường Quàng"@en
    "Mậu Thạch"@en
    "Mỹ Hào"@en
    "Mỹ Đức"@en
    "Nam Dong Hung"@en
    "Nam Gianh"@en
    "Nam Hai Lang"@en
    "Nam Hoa Lu"@en
    "Nam Hoa Lư"@en
    "Nam Hải Lăng"@en
    "Nam Thai Ninh"@en
    "Nam Thuy Anh"@en
    "Nam Thái Ninh"@en
    "Nam Thụy Anh"@en
    "Nam Tien Hung"@en
    "Nam Tiên Hưng"@en
    "Nam Truc"@en
    "Nam Trực"@en
    "Nam Đông Hưng"@en
    "Nghi Loc"@en
    "Nghi Lộc"@en
    "Ngu Thien"@en
    "Nguyen Du"@en
    "Nguyễn Du"@en
    "Ngự Thiên"@en
    "Ninh Giang"@en
    "Pho Hien"@en
    "Pho Yen"@en
    "Phong Doanh"@en
    "Phu Binh"@en
    "Phu Duc"@en
    "Phu Hoa 1"@en
    "Phu Hoa 2"@en
    "Phu Vang"@en
    "Phu Yen"@en
    "Phuc Yen"@en
    "Phuong An Phong"@en
    "Phuong Cam Pha"@en
    "Phuong Chu Van An"@en
    "Phuong Dong Ha"@en
    "Phuong Dong Hai"@en
    "Phuong Duong Kinh"@en
    "Phuong Duy Tien"@en
    "Phuong Ky Lua"@en
    "Phuong Le Dai Hanh"@en
    "Phuong Le Ich Moc"@en
    "Phuong My Hao"@en
    "Phuong Nam Hoa Lu"@en
    "Phuong Pho Hien"@en
    "Phuong Pho Yen"@en
    "Phuong Phu Yen"@en
    "Phuong Phuc Yen"@en
    "Phuong Song Cong"@en
    "Phuong Tan Mai"@en
    "Phuong Thai Binh"@en
    "Phuong Thanh Vinh"@en
    "Phuong Uong Bi"@en
    "Phuong Van Xuan"@en
    "Phuong Viet Tri"@en
    "Phuong Vinh Hung"@en
    "Phuong Yen Tu"@en
    "Phú Bình"@en
    "Phú Hòa 1"@en
    "Phú Hòa 2"@en
    "Phú Vang"@en
    "Phú Yên"@en
    "Phúc Yên"@en
    "Phường An Phong"@en
    "Phường Chu Văn An"@en
    "Phường Cẩm Phả"@en
    "Phường Duy Tiên"@en
    "Phường Dương Kinh"@en
    "Phường Kỳ Lừa"@en
    "Phường Lê Ích Mộc"@en
    "Phường Lê Đại Hành"@en
    "Phường Mỹ Hào"@en
    "Phường Nam Hoa Lư"@en
    "Phường Phú Yên"@en
    "Phường Phúc Yên"@en
    "Phường Phố Hiến"@en
    "Phường Phổ Yên"@en
    "Phường Sông Công"@en
    "Phường Thành Vinh"@en
    "Phường Thái Bình"@en
    "Phường Tân Mai"@en
    "Phường Uông Bí"@en
    "Phường Vinh Hưng"@en
    "Phường Việt Trì"@en
    "Phường Vạn Xuân"@en
    "Phường Yên Tử"@en
    "Phường Đông Hà"@en
    "Phường Đông Hải"@en
    "Phố Hiến"@en
    "Phổ Yên"@en
    "Phụ Dực"@en
    "Quan Thanh"@en
    "Quan Thành"@en
    "Quang Chau"@en
    "Quang Hung"@en
    "Quang Hưng"@en
    "Que Phong"@en
    "Quynh An"@en
    "Quynh Anh"@en
    "Quynh Luu"@en
    "Quynh Nhai"@en
    "Quynh Phu"@en
    "Quynh Son"@en
    "Quảng Châu"@en
    "Quế Phong"@en
    "Quỳnh An"@en
    "Quỳnh Anh"@en
    "Quỳnh Lưu"@en
    "Quỳnh Nhai"@en
    "Quỳnh Phú"@en
    "Quỳnh Phụ"@en
    "Quỳnh Sơn"@en
    "Son Lam"@en
    "Song Cong"@en
    "Sông Công"@en
    "Sơn Lâm"@en
    "Ta Dung"@en
    "Tam Nong"@en
    "Tam Nông"@en
    "Tan Chau"@en
    "Tan Mai"@en
    "Tan Minh"@en
    "Tan Tien"@en
    "Tay Thai Ninh"@en
    "Tay Thuy Anh"@en
    "Tay Tien Hai"@en
    "Thai Binh"@en
    "Thai Ninh"@en
    "Than Khe"@en
    "Thanh Binh Tho"@en
    "Thanh Liem"@en
    "Thanh Liêm"@en
    "Thanh Vinh"@en
    "Thuy Anh"@en
    "Thành Bình Thọ"@en
    "Thành Vinh"@en
    "Thái Bình"@en
    "Thái Ninh"@en
    "Thần Khê"@en
    "Thụy Anh"@en
    "Tien Hoa"@en
    "Tien Hung"@en
    "Tien La"@en
    "Tien Lu"@en
    "Tiên Hoa"@en
    "Tiên Hưng"@en
    "Tiên La"@en
    "Tiên Lữ"@en
    "Trang Dinh"@en
    "Trieu Binh"@en
    "Trieu Phong"@en
    "Trieu Viet Vuong"@en
    "Triệu Bình"@en
    "Triệu Phong"@en
    "Triệu Việt Vương"@en
    "Truc Ninh"@en
    "Truong Luu"@en
    "Tràng Định"@en
    "Trường Lưu"@en
    "Trực Ninh"@en
    "Tue Tinh"@en
    "Tuong Duong"@en
    "Tuy An Bac"@en
    "Tuy An Bắc"@en
    "Tuệ Tĩnh"@en
    "Tà Đùng"@en
    "Tân Châu"@en
    "Tân Mai"@en
    "Tân Minh"@en
    "Tân Tiến"@en
    "Tây Thái Ninh"@en
    "Tây Thụy Anh"@en
    "Tây Tiền Hải"@en
    "Tương Dương"@en
    "Uong Bi"@en
    "Uông Bí"@en
    "Van An"@en
    "Van Du"@en
    "Van Kieu"@en
    "Van Lang"@en
    "Van Phu"@en
    "Van Thang"@en
    "Van Xuan"@en
    "Viet Tien"@en
    "Viet Tri"@en
    "Viet Yen"@en
    "Vinh Hung"@en
    "Vinh Hưng"@en
    "Vinh Loc"@en
    "Vinh Lộc"@en
    "Vinh Thuan"@en
    "Việt Tiến"@en
    "Việt Trì"@en
    "Việt Yên"@en
    "Vo Nhai"@en
    "Vu Duong"@en
    "Vân Du"@en
    "Võ Nhai"@en
    "Văn Kiều"@en
    "Văn Lãng"@en
    "Vĩnh Thuận"@en
    "Vũ Dương"@en
    "Vạn An"@en
    "Vạn Phú"@en
    "Vạn Thắng"@en
    "Vạn Xuân"@en
    "Xa A Sao"@en
    "Xa An Chau"@en
    "Xa An Khanh"@en
    "Xa An Quang"@en
    "Xa Bac Dong Hung"@en
    "Xa Bac Dong Quan"@en
    "Xa Bac Thai Ninh"@en
    "Xa Bac Thuy Anh"@en
    "Xa Bac Tien Hung"@en
    "Xa Ben Hai"@en
    "Xa Bich Hao"@en
    "Xa Binh Minh"@en
    "Xa Binh Son"@en
    "Xa Cat Ngan"@en
    "Xa Chau Ninh"@en
    "Xa Chi Minh"@en
    "Xa Con Tien"@en
    "Xa Dak Song"@en
    "Xa Dan Dien"@en
    "Xa Dong Bang"@en
    "Xa Dong Chau"@en
    "Xa Dong Loc"@en
    "Xa Dong Thai Ninh"@en
    "Xa Dong Thanh"@en
    "Xa Dong Thinh"@en
    "Xa Dong Thuy Anh"@en
    "Xa Dong Tien Hai"@en
    "Xa Dong Tien Hung"@en
    "Xa Duc Chau"@en
    "Xa Duc Lap"@en
    "Xa Duc Minh"@en
    "Xa Duong An"@en
    "Xa Giao Binh"@en
    "Xa Giao Minh"@en
    "Xa Giao Ninh"@en
    "Xa Giao Thuy"@en
    "Xa Hai Hau"@en
    "Xa Hai Hung"@en
    "Xa Hai Lang"@en
    "Xa Hai Loc"@en
    "Xa Hai Thinh"@en
    "Xa Hoa Lac"@en
    "Xa Hong Chau"@en
    "Xa Hong Phong"@en
    "Xa Hung Dao"@en
    "Xa Kim Anh"@en
    "Xa Kim Bang"@en
    "Xa Kim Son"@en
    "Xa Ky Anh"@en
    "Xa Lam Thanh"@en
    "Xa Lien Son Lak"@en
    "Xa Luong Son"@en
    "Xa Mai Son"@en
    "Xa Mau Thach"@en
    "Xa Minh Thai"@en
    "Xa Muong Ham"@en
    "Xa Muong La"@en
    "Xa Muong Quang"@en
    "Xa My Duc"@en
    "Xa Nam Dong Hung"@en
    "Xa Nam Gianh"@en
    "Xa Nam Hai Lang"@en
    "Xa Nam Thai Ninh"@en
    "Xa Nam Thuy Anh"@en
    "Xa Nam Tien Hung"@en
    "Xa Nam Truc"@en
    "Xa Nghi Loc"@en
    "Xa Ngu Thien"@en
    "Xa Nguyen Du"@en
    "Xa Ninh Giang"@en
    "Xa Phong Doanh"@en
    "Xa Phu Binh"@en
    "Xa Phu Duc"@en
    "Xa Phu Hoa 1"@en
    "Xa Phu Hoa 2"@en
    "Xa Phu Vang"@en
    "Xa Quan Thanh"@en
    "Xa Quang Chau"@en
    "Xa Quang Hung"@en
    "Xa Que Phong"@en
    "Xa Quynh An"@en
    "Xa Quynh Anh"@en
    "Xa Quynh Luu"@en
    "Xa Quynh Nhai"@en
    "Xa Quynh Phu"@en
    "Xa Quynh Son"@en
    "Xa Son Lam"@en
    "Xa Ta Dung"@en
    "Xa Tam Nong"@en
    "Xa Tan Chau"@en
    "Xa Tan Minh"@en
    "Xa Tan Tien"@en
    "Xa Tay Thai Ninh"@en
    "Xa Tay Thuy Anh"@en
    "Xa Tay Tien Hai"@en
    "Xa Thai Ninh"@en
    "Xa Than Khe"@en
    "Xa Thanh Binh Tho"@en
    "Xa Thanh Liem"@en
    "Xa Thuy Anh"@en
    "Xa Tien Hoa"@en
    "Xa Tien Hung"@en
    "Xa Tien La"@en
    "Xa Tien Lu"@en
    "Xa Trang Dinh"@en
    "Xa Trieu Binh"@en
    "Xa Trieu Phong"@en
    "Xa Trieu Viet Vuong"@en
    "Xa Truc Ninh"@en
    "Xa Truong Luu"@en
    "Xa Tue Tinh"@en
    "Xa Tuong Duong"@en
    "Xa Tuy An Bac"@en
    "Xa Van An"@en
    "Xa Van Du"@en
    "Xa Van Kieu"@en
    "Xa Van Lang"@en
    "Xa Van Phu"@en
    "Xa Van Thang"@en
    "Xa Van Xuan"@en
    "Xa Viet Tien"@en
    "Xa Viet Yen"@en
    "Xa Vinh Loc"@en
    "Xa Vinh Thuan"@en
    "Xa Vo Nhai"@en
    "Xa Vu Duong"@en
    "Xa Xuan Giang"@en
    "Xa Xuan Hung"@en
    "Xa Y Yen"@en
    "Xa Yen Xuan"@en
    "Xuan Giang"@en
    "Xuan Hung"@en
    "Xuân Giang"@en
    "Xuân Hưng"@en
    "Xã A Sào"@en
    "Xã An Châu"@en
    "Xã An Khánh"@en
    "Xã An Quang"@en
    "Xã Bình Minh"@en
    "Xã Bình Sơn"@en
    "Xã Bích Hào"@en
    "Xã Bắc Thái Ninh"@en
    "Xã Bắc Thụy Anh"@en
    "Xã Bắc Tiên Hưng"@en
    "Xã Bắc Đông Hưng"@en
    "Xã Bắc Đông Quan"@en
    "Xã Bến Hải"@en
    "Xã Châu Ninh"@en
    "Xã Chí Minh"@en
    "Xã Cát Ngạn"@en
    "Xã Cồn Tiên"@en
    "Xã Giao Bình"@en
    "Xã Giao Minh"@en
    "Xã Giao Ninh"@en
    "Xã Giao Thuỷ"@en
    "Xã Hòa Lạc"@en
    "Xã Hưng Đạo"@en
    "Xã Hải Hưng"@en
    "Xã Hải Hậu"@en
    "Xã Hải Lăng"@en
    "Xã Hải Lộc"@en
    "Xã Hải Thịnh"@en
    "Xã Hồng Châu"@en
    "Xã Hồng Phong"@en
    "Xã Kim Anh"@en
    "Xã Kim Bảng"@en
    "Xã Kim Sơn"@en
    "Xã Kỳ Anh"@en
    "Xã Lam Thành"@en
    "Xã Liên Sơn Lắk"@en
    "Xã Lương Sơn"@en
    "Xã Mai Sơn"@en
    "Xã Minh Thái"@en
    "Xã Mường Ham"@en
    "Xã Mường La"@en
    "Xã Mường Quàng"@en
    "Xã Mậu Thạch"@en
    "Xã Mỹ Đức"@en
    "Xã Nam Gianh"@en
    "Xã Nam Hải Lăng"@en
    "Xã Nam Thái Ninh"@en
    "Xã Nam Thụy Anh"@en
    "Xã Nam Tiên Hưng"@en
    "Xã Nam Trực"@en
    "Xã Nam Đông Hưng"@en
    "Xã Nghi Lộc"@en
    "Xã Nguyễn Du"@en
    "Xã Ngự Thiên"@en
    "Xã Ninh Giang"@en
    "Xã Phong Doanh"@en
    "Xã Phú Bình"@en
    "Xã Phú Hòa 1"@en
    "Xã Phú Hòa 2"@en
    "Xã Phú Vang"@en
    "Xã Phụ Dực"@en
    "Xã Quan Thành"@en
    "Xã Quang Hưng"@en
    "Xã Quảng Châu"@en
    "Xã Quế Phong"@en
    "Xã Quỳnh An"@en
    "Xã Quỳnh Anh"@en
    "Xã Quỳnh Lưu"@en
    "Xã Quỳnh Nhai"@en
    "Xã Quỳnh Phú"@en
    "Xã Quỳnh Phụ"@en
    "Xã Quỳnh Sơn"@en
    "Xã Sơn Lâm"@en
    "Xã Tam Nông"@en
    "Xã Thanh Liêm"@en
    "Xã Thành Bình Thọ"@en
    "Xã Thái Ninh"@en
    "Xã Thần Khê"@en
    "Xã Thụy Anh"@en
    "Xã Tiên Hoa"@en
    "Xã Tiên Hưng"@en
    "Xã Tiên La"@en
    "Xã Tiên Lữ"@en
    "Xã Triệu Bình"@en
    "Xã Triệu Phong"@en
    "Xã Triệu Việt Vương"@en
    "Xã Tràng Định"@en
    "Xã Trường Lưu"@en
    "Xã Trực Ninh"@en
    "Xã Tuy An Bắc"@en
    "Xã Tuệ Tĩnh"@en
    "Xã Tà Đùng"@en
    "Xã Tân Châu"@en
    "Xã Tân Minh"@en
    "Xã Tân Tiến"@en
    "Xã Tây Thái Ninh"@en
    "Xã Tây Thụy Anh"@en
    "Xã Tây Tiền Hải"@en
    "Xã Tương Dương"@en
    "Xã Vinh Lộc"@en
    "Xã Việt Tiến"@en
    "Xã Việt Yên"@en
    "Xã Vân Du"@en
    "Xã Võ Nhai"@en
    "Xã Văn Kiều"@en
    "Xã Văn Lãng"@en
    "Xã Vĩnh Thuận"@en
    "Xã Vũ Dương"@en
    "Xã Vạn An"@en
    "Xã Vạn Phú"@en
    "Xã Vạn Thắng"@en
    "Xã Vạn Xuân"@en
    "Xã Xuân Giang"@en
    "Xã Xuân Hưng"@en
    "Xã Yên Xuân"@en
    "Xã Ý Yên"@en
    "Xã Đan Điền"@en
    "Xã Đông Lộc"@en
    "Xã Đông Thành"@en
    "Xã Đông Thái Ninh"@en
    "Xã Đông Thụy Anh"@en
    "Xã Đông Tiên Hưng"@en
    "Xã Đông Tiền Hải"@en
    "Xã Đường An"@en
    "Xã Đắk Song"@en
    "Xã Đồng Bằng"@en
    "Xã Đồng Châu"@en
    "Xã Đồng Thịnh"@en
    "Xã Đức Châu"@en
    "Xã Đức Lập"@en
    "Xã Đức Minh"@en
    "Y Yen"@en
    "Yen Tu"@en
    "Yen Xuan"@en
    "Yên Tử"@en
    "Yên Xuân"@en
    "Ý Yên"@en
    "Đan Điền"@en
    "Đông Hà"@en
    "Đông Hải"@en
    "Đông Lộc"@en
    "Đông Thành"@en
    "Đông Thái Ninh"@en
    "Đông Thụy Anh"@en
    "Đông Tiên Hưng"@en
    "Đông Tiền Hải"@en
    "Đường An"@en
    "Đắk Song"@en
    "Đồng Bằng"@en
    "Đồng Châu"@en
    "Đồng Thịnh"@en
    "Đức Châu"@en
    "Đức Lập"@en
    "Đức Minh"@en
    "A Sao"@vi
    "A Sào"@vi
    "An Chau"@vi
    "An Châu"@vi
    "An Khanh"@vi
    "An Khánh"@vi
    "An Phong"@vi
    "An Quang"@vi
    "Bac Dong Hung"@vi
    "Bac Dong Quan"@vi
    "Bac Thai Ninh"@vi
    "Bac Thuy Anh"@vi
    "Bac Tien Hung"@vi
    "Ben Hai"@vi
    "Bich Hao"@vi
    "Binh Minh"@vi
    "Binh Son"@vi
    "Bình Minh"@vi
    "Bình Sơn"@vi
    "Bích Hào"@vi
    "Bắc Thái Ninh"@vi
    "Bắc Thụy Anh"@vi
    "Bắc Tiên Hưng"@vi
    "Bắc Đông Hưng"@vi
    "Bắc Đông Quan"@vi
    "Bến Hải"@vi
    "Cam Pha"@vi
    "Cat Ngan"@vi
    "Chau Ninh"@vi
    "Chi Minh"@vi
    "Chu Van An"@vi
    "Chu Văn An"@vi
    "Châu Ninh"@vi
    "Chí Minh"@vi
    "Con Tien"@vi
    "Cát Ngạn"@vi
    "Cẩm Phả"@vi
    "Cồn Tiên"@vi
    "Dak Song"@vi
    "Dan Dien"@vi
    "Dong Bang"@vi
    "Dong Chau"@vi
    "Dong Ha"@vi
    "Dong Hai"@vi
    "Dong Loc"@vi
    "Dong Thai Ninh"@vi
    "Dong Thanh"@vi
    "Dong Thinh"@vi
    "Dong Thuy Anh"@vi
    "Dong Tien Hai"@vi
    "Dong Tien Hung"@vi
    "Duc Chau"@vi
    "Duc Lap"@vi
    "Duc Minh"@vi
    "Duong An"@vi
    "Duong Kinh"@vi
    "Duy Tien"@vi
    "Duy Tiên"@vi
    "Dương Kinh"@vi
    "Giao Binh"@vi
    "Giao Bình"@vi
    "Giao Minh"@vi
    "Giao Ninh"@vi
    "Giao Thuy"@vi
    "Giao Thuỷ"@vi
    "Hai Hau"@vi
    "Hai Hung"@vi
    "Hai Lang"@vi
    "Hai Loc"@vi
    "Hai Thinh"@vi
    "Hoa Lac"@vi
    "Hong Chau"@vi
    "Hong Phong"@vi
    "Hung Dao"@vi
    "Hòa Lạc"@vi
    "Hưng Đạo"@vi
    "Hải Hưng"@vi
    "Hải Hậu"@vi
    "Hải Lăng"@vi
    "Hải Lộc"@vi
    "Hải Thịnh"@vi
    "Hồng Châu"@vi
    "Hồng Phong"@vi
    "Kim Anh"@vi
    "Kim Bang"@vi
    "Kim Bảng"@vi
    "Kim Son"@vi
    "Kim Sơn"@vi
    "Ky Anh"@vi
    "Ky Lua"@vi
    "Kỳ Anh"@vi
    "Kỳ Lừa"@vi
    "Lam Thanh"@vi
    "Lam Thành"@vi
    "Le Dai Hanh"@vi
    "Le Ich Moc"@vi
    "Lien Son Lak"@vi
    "Liên Sơn Lắk"@vi
    "Luong Son"@vi
    "Lê Ích Mộc"@vi
    "Lê Đại Hành"@vi
    "Lương Sơn"@vi
    "Mai Son"@vi
    "Mai Sơn"@vi
    "Mau Thach"@vi
    "Minh Thai"@vi
    "Minh Thái"@vi
    "Muong Ham"@vi
    "Muong La"@vi
    "Muong Quang"@vi
    "My Duc"@vi
    "My Hao"@vi
    "Mường Ham"@vi
    "Mường La"@vi
    "Mường Quàng"@vi
    "Mậu Thạch"@vi
    "Mỹ Hào"@vi
    "Mỹ Đức"@vi
    "Nam Dong Hung"@vi
    "Nam Gianh"@vi
    "Nam Hai Lang"@vi
    "Nam Hoa Lu"@vi
    "Nam Hoa Lư"@vi
    "Nam Hải Lăng"@vi
    "Nam Thai Ninh"@vi
    "Nam Thuy Anh"@vi
    "Nam Thái Ninh"@vi
    "Nam Thụy Anh"@vi
    "Nam Tien Hung"@vi
    "Nam Tiên Hưng"@vi
    "Nam Truc"@vi
    "Nam Trực"@vi
    "Nam Đông Hưng"@vi
    "Nghi Loc"@vi
    "Nghi Lộc"@vi
    "Ngu Thien"@vi
    "Nguyen Du"@vi
    "Nguyễn Du"@vi
    "Ngự Thiên"@vi
    "Ninh Giang"@vi
    "Pho Hien"@vi
    "Pho Yen"@vi
    "Phong Doanh"@vi
    "Phu Binh"@vi
    "Phu Duc"@vi
    "Phu Hoa 1"@vi
    "Phu Hoa 2"@vi
    "Phu Vang"@vi
    "Phu Yen"@vi
    "Phuc Yen"@vi
    "Phuong An Phong"@vi
    "Phuong Cam Pha"@vi
    "Phuong Chu Van An"@vi
    "Phuong Dong Ha"@vi
    "Phuong Dong Hai"@vi
    "Phuong Duong Kinh"@vi
    "Phuong Duy Tien"@vi
    "Phuong Ky Lua"@vi
    "Phuong Le Dai Hanh"@vi
    "Phuong Le Ich Moc"@vi
    "Phuong My Hao"@vi
    "Phuong Nam Hoa Lu"@vi
    "Phuong Pho Hien"@vi
    "Phuong Pho Yen"@vi
    "Phuong Phu Yen"@vi
    "Phuong Phuc Yen"@vi
    "Phuong Song Cong"@vi
    "Phuong Tan Mai"@vi
    "Phuong Thai Binh"@vi
    "Phuong Thanh Vinh"@vi
    "Phuong Uong Bi"@vi
    "Phuong Van Xuan"@vi
    "Phuong Viet Tri"@vi
    "Phuong Vinh Hung"@vi
    "Phuong Yen Tu"@vi
    "Phú Bình"@vi
    "Phú Hòa 1"@vi
    "Phú Hòa 2"@vi
    "Phú Vang"@vi
    "Phú Yên"@vi
    "Phúc Yên"@vi
    "Phường An Phong"@vi
    "Phường Chu Văn An"@vi
    "Phường Cẩm Phả"@vi
    "Phường Duy Tiên"@vi
    "Phường Dương Kinh"@vi
    "Phường Kỳ Lừa"@vi
    "Phường Lê Ích Mộc"@vi
    "Phường Lê Đại Hành"@vi
    "Phường Mỹ Hào"@vi
    "Phường Nam Hoa Lư"@vi
    "Phường Phú Yên"@vi
    "Phường Phúc Yên"@vi
    "Phường Phố Hiến"@vi
    "Phường Phổ Yên"@vi
    "Phường Sông Công"@vi
    "Phường Thành Vinh"@vi
    "Phường Thái Bình"@vi
    "Phường Tân Mai"@vi
    "Phường Uông Bí"@vi
    "Phường Vinh Hưng"@vi
    "Phường Việt Trì"@vi
    "Phường Vạn Xuân"@vi
    "Phường Yên Tử"@vi
    "Phường Đông Hà"@vi
    "Phường Đông Hải"@vi
    "Phố Hiến"@vi
    "Phổ Yên"@vi
    "Phụ Dực"@vi
    "Quan Thanh"@vi
    "Quan Thành"@vi
    "Quang Chau"@vi
    "Quang Hung"@vi
    "Quang Hưng"@vi
    "Que Phong"@vi
    "Quynh An"@vi
    "Quynh Anh"@vi
    "Quynh Luu"@vi
    "Quynh Nhai"@vi
    "Quynh Phu"@vi
    "Quynh Son"@vi
    "Quảng Châu"@vi
    "Quế Phong"@vi
    "Quỳnh An"@vi
    "Quỳnh Anh"@vi
    "Quỳnh Lưu"@vi
    "Quỳnh Nhai"@vi
    "Quỳnh Phú"@vi
    "Quỳnh Phụ"@vi
    "Quỳnh Sơn"@vi
    "Son Lam"@vi
    "Song Cong"@vi
    "Sông Công"@vi
    "Sơn Lâm"@vi
    "Ta Dung"@vi
    "Tam Nong"@vi
    "Tam Nông"@vi
    "Tan Chau"@vi
    "Tan Mai"@vi
    "Tan Minh"@vi
    "Tan Tien"@vi
    "Tay Thai Ninh"@vi
    "Tay Thuy Anh"@vi
    "Tay Tien Hai"@vi
    "Thai Binh"@vi
    "Thai Ninh"@vi
    "Than Khe"@vi
    "Thanh Binh Tho"@vi
    "Thanh Liem"@vi
    "Thanh Liêm"@vi
    "Thanh Vinh"@vi
    "Thuy Anh"@vi
    "Thành Bình Thọ"@vi
    "Thành Vinh"@vi
    "Thái Bình"@vi
    "Thái Ninh"@vi
    "Thần Khê"@vi
    "Thụy Anh"@vi
    "Tien Hoa"@vi
    "Tien Hung"@vi
    "Tien La"@vi
    "Tien Lu"@vi
    "Tiên Hoa"@vi
    "Tiên Hưng"@vi
    "Tiên La"@vi
    "Tiên Lữ"@vi
    "Trang Dinh"@vi
    "Trieu Binh"@vi
    "Trieu Phong"@vi
    "Trieu Viet Vuong"@vi
    "Triệu Bình"@vi
    "Triệu Phong"@vi
    "Triệu Việt Vương"@vi
    "Truc Ninh"@vi
    "Truong Luu"@vi
    "Tràng Định"@vi
    "Trường Lưu"@vi
    "Trực Ninh"@vi
    "Tue Tinh"@vi
    "Tuong Duong"@vi
    "Tuy An Bac"@vi
    "Tuy An Bắc"@vi
    "Tuệ Tĩnh"@vi
    "Tà Đùng"@vi
    "Tân Châu"@vi
    "Tân Mai"@vi
    "Tân Minh"@vi
    "Tân Tiến"@vi
    "Tây Thái Ninh"@vi
    "Tây Thụy Anh"@vi
    "Tây Tiền Hải"@vi
    "Tương Dương"@vi
    "Uong Bi"@vi
    "Uông Bí"@vi
    "Van An"@vi
    "Van Du"@vi
    "Van Kieu"@vi
    "Van Lang"@vi
    "Van Phu"@vi
    "Van Thang"@vi
    "Van Xuan"@vi
    "Viet Tien"@vi
    "Viet Tri"@vi
    "Viet Yen"@vi
    "Vinh Hung"@vi
    "Vinh Hưng"@vi
    "Vinh Loc"@vi
    "Vinh Lộc"@vi
    "Vinh Thuan"@vi
    "Việt Tiến"@vi
    "Việt Trì"@vi
    "Việt Yên"@vi
    "Vo Nhai"@vi
    "Vu Duong"@vi
    "Vân Du"@vi
    "Võ Nhai"@vi
    "Văn Kiều"@vi
    "Văn Lãng"@vi
    "Vĩnh Thuận"@vi
    "Vũ Dương"@vi
    "Vạn An"@vi
    "Vạn Phú"@vi
    "Vạn Thắng"@vi
    "Vạn Xuân"@vi
    "Xa A Sao"@vi
    "Xa An Chau"@vi
    "Xa An Khanh"@vi
    "Xa An Quang"@vi
    "Xa Bac Dong Hung"@vi
    "Xa Bac Dong Quan"@vi
    "Xa Bac Thai Ninh"@vi
    "Xa Bac Thuy Anh"@vi
    "Xa Bac Tien Hung"@vi
    "Xa Ben Hai"@vi
    "Xa Bich Hao"@vi
    "Xa Binh Minh"@vi
    "Xa Binh Son"@vi
    "Xa Cat Ngan"@vi
    "Xa Chau Ninh"@vi
    "Xa Chi Minh"@vi
    "Xa Con Tien"@vi
    "Xa Dak Song"@vi
    "Xa Dan Dien"@vi
    "Xa Dong Bang"@vi
    "Xa Dong Chau"@vi
    "Xa Dong Loc"@vi
    "Xa Dong Thai Ninh"@vi
    "Xa Dong Thanh"@vi
    "Xa Dong Thinh"@vi
    "Xa Dong Thuy Anh"@vi
    "Xa Dong Tien Hai"@vi
    "Xa Dong Tien Hung"@vi
    "Xa Duc Chau"@vi
    "Xa Duc Lap"@vi
    "Xa Duc Minh"@vi
    "Xa Duong An"@vi
    "Xa Giao Binh"@vi
    "Xa Giao Minh"@vi
    "Xa Giao Ninh"@vi
    "Xa Giao Thuy"@vi
    "Xa Hai Hau"@vi
    "Xa Hai Hung"@vi
    "Xa Hai Lang"@vi
    "Xa Hai Loc"@vi
    "Xa Hai Thinh"@vi
    "Xa Hoa Lac"@vi
    "Xa Hong Chau"@vi
    "Xa Hong Phong"@vi
    "Xa Hung Dao"@vi
    "Xa Kim Anh"@vi
    "Xa Kim Bang"@vi
    "Xa Kim Son"@vi
    "Xa Ky Anh"@vi
    "Xa Lam Thanh"@vi
    "Xa Lien Son Lak"@vi
    "Xa Luong Son"@vi
    "Xa Mai Son"@vi
    "Xa Mau Thach"@vi
    "Xa Minh Thai"@vi
    "Xa Muong Ham"@vi
    "Xa Muong La"@vi
    "Xa Muong Quang"@vi
    "Xa My Duc"@vi
    "Xa Nam Dong Hung"@vi
    "Xa Nam Gianh"@vi
    "Xa Nam Hai Lang"@vi
    "Xa Nam Thai Ninh"@vi
    "Xa Nam Thuy Anh"@vi
    "Xa Nam Tien Hung"@vi
    "Xa Nam Truc"@vi
    "Xa Nghi Loc"@vi
    "Xa Ngu Thien"@vi
    "Xa Nguyen Du"@vi
    "Xa Ninh Giang"@vi
    "Xa Phong Doanh"@vi
    "Xa Phu Binh"@vi
    "Xa Phu Duc"@vi
    "Xa Phu Hoa 1"@vi
    "Xa Phu Hoa 2"@vi
    "Xa Phu Vang"@vi
    "Xa Quan Thanh"@vi
    "Xa Quang Chau"@vi
    "Xa Quang Hung"@vi
    "Xa Que Phong"@vi
    "Xa Quynh An"@vi
    "Xa Quynh Anh"@vi
    "Xa Quynh Luu"@vi
    "Xa Quynh Nhai"@vi
    "Xa Quynh Phu"@vi
    "Xa Quynh Son"@vi
    "Xa Son Lam"@vi
    "Xa Ta Dung"@vi
    "Xa Tam Nong"@vi
    "Xa Tan Chau"@vi
    "Xa Tan Minh"@vi
    "Xa Tan Tien"@vi
    "Xa Tay Thai Ninh"@vi
    "Xa Tay Thuy Anh"@vi
    "Xa Tay Tien Hai"@vi
    "Xa Thai Ninh"@vi
    "Xa Than Khe"@vi
    "Xa Thanh Binh Tho"@vi
    "Xa Thanh Liem"@vi
    "Xa Thuy Anh"@vi
    "Xa Tien Hoa"@vi
    "Xa Tien Hung"@vi
    "Xa Tien La"@vi
    "Xa Tien Lu"@vi
    "Xa Trang Dinh"@vi
    "Xa Trieu Binh"@vi
    "Xa Trieu Phong"@vi
    "Xa Trieu Viet Vuong"@vi
    "Xa Truc Ninh"@vi
    "Xa Truong Luu"@vi
    "Xa Tue Tinh"@vi
    "Xa Tuong Duong"@vi
    "Xa Tuy An Bac"@vi
    "Xa Van An"@vi
    "Xa Van Du"@vi
    "Xa Van Kieu"@vi
    "Xa Van Lang"@vi
    "Xa Van Phu"@vi
    "Xa Van Thang"@vi
    "Xa Van Xuan"@vi
    "Xa Viet Tien"@vi
    "Xa Viet Yen"@vi
    "Xa Vinh Loc"@vi
    "Xa Vinh Thuan"@vi
    "Xa Vo Nhai"@vi
    "Xa Vu Duong"@vi
    "Xa Xuan Giang"@vi
    "Xa Xuan Hung"@vi
    "Xa Y Yen"@vi
    "Xa Yen Xuan"@vi
    "Xuan Giang"@vi
    "Xuan Hung"@vi
    "Xuân Giang"@vi
    "Xuân Hưng"@vi
    "Xã A Sào"@vi
    "Xã An Châu"@vi
    "Xã An Khánh"@vi
    "Xã An Quang"@vi
    "Xã Bình Minh"@vi
    "Xã Bình Sơn"@vi
    "Xã Bích Hào"@vi
    "Xã Bắc Thái Ninh"@vi
    "Xã Bắc Thụy Anh"@vi
    "Xã Bắc Tiên Hưng"@vi
    "Xã Bắc Đông Hưng"@vi
    "Xã Bắc Đông Quan"@vi
    "Xã Bến Hải"@vi
    "Xã Châu Ninh"@vi
    "Xã Chí Minh"@vi
    "Xã Cát Ngạn"@vi
    "Xã Cồn Tiên"@vi
    "Xã Giao Bình"@vi
    "Xã Giao Minh"@vi
    "Xã Giao Ninh"@vi
    "Xã Giao Thuỷ"@vi
    "Xã Hòa Lạc"@vi
    "Xã Hưng Đạo"@vi
    "Xã Hải Hưng"@vi
    "Xã Hải Hậu"@vi
    "Xã Hải Lăng"@vi
    "Xã Hải Lộc"@vi
    "Xã Hải Thịnh"@vi
    "Xã Hồng Châu"@vi
    "Xã Hồng Phong"@vi
    "Xã Kim Anh"@vi
    "Xã Kim Bảng"@vi
    "Xã Kim Sơn"@vi
    "Xã Kỳ Anh"@vi
    "Xã Lam Thành"@vi
    "Xã Liên Sơn Lắk"@vi
    "Xã Lương Sơn"@vi
    "Xã Mai Sơn"@vi
    "Xã Minh Thái"@vi
    "Xã Mường Ham"@vi
    "Xã Mường La"@vi
    "Xã Mường Quàng"@vi
    "Xã Mậu Thạch"@vi
    "Xã Mỹ Đức"@vi
    "Xã Nam Gianh"@vi
    "Xã Nam Hải Lăng"@vi
    "Xã Nam Thái Ninh"@vi
    "Xã Nam Thụy Anh"@vi
    "Xã Nam Tiên Hưng"@vi
    "Xã Nam Trực"@vi
    "Xã Nam Đông Hưng"@vi
    "Xã Nghi Lộc"@vi
    "Xã Nguyễn Du"@vi
    "Xã Ngự Thiên"@vi
    "Xã Ninh Giang"@vi
    "Xã Phong Doanh"@vi
    "Xã Phú Bình"@vi
    "Xã Phú Hòa 1"@vi
    "Xã Phú Hòa 2"@vi
    "Xã Phú Vang"@vi
    "Xã Phụ Dực"@vi
    "Xã Quan Thành"@vi
    "Xã Quang Hưng"@vi
    "Xã Quảng Châu"@vi
    "Xã Quế Phong"@vi
    "Xã Quỳnh An"@vi
    "Xã Quỳnh Anh"@vi
    "Xã Quỳnh Lưu"@vi
    "Xã Quỳnh Nhai"@vi
    "Xã Quỳnh Phú"@vi
    "Xã Quỳnh Phụ"@vi
    "Xã Quỳnh Sơn"@vi
    "Xã Sơn Lâm"@vi
    "Xã Tam Nông"@vi
    "Xã Thanh Liêm"@vi
    "Xã Thành Bình Thọ"@vi
    "Xã Thái Ninh"@vi
    "Xã Thần Khê"@vi
    "Xã Thụy Anh"@vi
    "Xã Tiên Hoa"@vi
    "Xã Tiên Hưng"@vi
    "Xã Tiên La"@vi
    "Xã Tiên Lữ"@vi
    "Xã Triệu Bình"@vi
    "Xã Triệu Phong"@vi
    "Xã Triệu Việt Vương"@vi
    "Xã Tràng Định"@vi
    "Xã Trường Lưu"@vi
    "Xã Trực Ninh"@vi
    "Xã Tuy An Bắc"@vi
    "Xã Tuệ Tĩnh"@vi
    "Xã Tà Đùng"@vi
    "Xã Tân Châu"@vi
    "Xã Tân Minh"@vi
    "Xã Tân Tiến"@vi
    "Xã Tây Thái Ninh"@vi
    "Xã Tây Thụy Anh"@vi
    "Xã Tây Tiền Hải"@vi
    "Xã Tương Dương"@vi
    "Xã Vinh Lộc"@vi
    "Xã Việt Tiến"@vi
    "Xã Việt Yên"@vi
    "Xã Vân Du"@vi
    "Xã Võ Nhai"@vi
    "Xã Văn Kiều"@vi
    "Xã Văn Lãng"@vi
    "Xã Vĩnh Thuận"@vi
    "Xã Vũ Dương"@vi
    "Xã Vạn An"@vi
    "Xã Vạn Phú"@vi
    "Xã Vạn Thắng"@vi
    "Xã Vạn Xuân"@vi
    "Xã Xuân Giang"@vi
    "Xã Xuân Hưng"@vi
    "Xã Yên Xuân"@vi
    "Xã Ý Yên"@vi
    "Xã Đan Điền"@vi
    "Xã Đông Lộc"@vi
    "Xã Đông Thành"@vi
    "Xã Đông Thái Ninh"@vi
    "Xã Đông Thụy Anh"@vi
    "Xã Đông Tiên Hưng"@vi
    "Xã Đông Tiền Hải"@vi
    "Xã Đường An"@vi
    "Xã Đắk Song"@vi
    "Xã Đồng Bằng"@vi
    "Xã Đồng Châu"@vi
    "Xã Đồng Thịnh"@vi
    "Xã Đức Châu"@vi
    "Xã Đức Lập"@vi
    "Xã Đức Minh"@vi
    "Y Yen"@vi
    "Yen Tu"@vi
    "Yen Xuan"@vi
    "Yên Tử"@vi
    "Yên Xuân"@vi
    "Ý Yên"@vi
    "Đan Điền"@vi
    "Đông Hà"@vi
    "Đông Hải"@vi
    "Đông Lộc"@vi
    "Đông Thành"@vi
    "Đông Thái Ninh"@vi
    "Đông Thụy Anh"@vi
    "Đông Tiên Hưng"@vi
    "Đông Tiền Hải"@vi
    "Đường An"@vi
    "Đắk Song"@vi
    "Đồng Bằng"@vi
    "Đồng Châu"@vi
    "Đồng Thịnh"@vi
    "Đức Châu"@vi
    "Đức Lập"@vi
    "Đức Minh"@vi
    }
    ?item rdfs:label ?matchedTerm .
    BIND("label" AS ?matchKind)
  }
  UNION
  {
    VALUES ?matchedTerm {
    "A Sao"@en
    "A Sào"@en
    "An Chau"@en
    "An Châu"@en
    "An Khanh"@en
    "An Khánh"@en
    "An Phong"@en
    "An Quang"@en
    "Bac Dong Hung"@en
    "Bac Dong Quan"@en
    "Bac Thai Ninh"@en
    "Bac Thuy Anh"@en
    "Bac Tien Hung"@en
    "Ben Hai"@en
    "Bich Hao"@en
    "Binh Minh"@en
    "Binh Son"@en
    "Bình Minh"@en
    "Bình Sơn"@en
    "Bích Hào"@en
    "Bắc Thái Ninh"@en
    "Bắc Thụy Anh"@en
    "Bắc Tiên Hưng"@en
    "Bắc Đông Hưng"@en
    "Bắc Đông Quan"@en
    "Bến Hải"@en
    "Cam Pha"@en
    "Cat Ngan"@en
    "Chau Ninh"@en
    "Chi Minh"@en
    "Chu Van An"@en
    "Chu Văn An"@en
    "Châu Ninh"@en
    "Chí Minh"@en
    "Con Tien"@en
    "Cát Ngạn"@en
    "Cẩm Phả"@en
    "Cồn Tiên"@en
    "Dak Song"@en
    "Dan Dien"@en
    "Dong Bang"@en
    "Dong Chau"@en
    "Dong Ha"@en
    "Dong Hai"@en
    "Dong Loc"@en
    "Dong Thai Ninh"@en
    "Dong Thanh"@en
    "Dong Thinh"@en
    "Dong Thuy Anh"@en
    "Dong Tien Hai"@en
    "Dong Tien Hung"@en
    "Duc Chau"@en
    "Duc Lap"@en
    "Duc Minh"@en
    "Duong An"@en
    "Duong Kinh"@en
    "Duy Tien"@en
    "Duy Tiên"@en
    "Dương Kinh"@en
    "Giao Binh"@en
    "Giao Bình"@en
    "Giao Minh"@en
    "Giao Ninh"@en
    "Giao Thuy"@en
    "Giao Thuỷ"@en
    "Hai Hau"@en
    "Hai Hung"@en
    "Hai Lang"@en
    "Hai Loc"@en
    "Hai Thinh"@en
    "Hoa Lac"@en
    "Hong Chau"@en
    "Hong Phong"@en
    "Hung Dao"@en
    "Hòa Lạc"@en
    "Hưng Đạo"@en
    "Hải Hưng"@en
    "Hải Hậu"@en
    "Hải Lăng"@en
    "Hải Lộc"@en
    "Hải Thịnh"@en
    "Hồng Châu"@en
    "Hồng Phong"@en
    "Kim Anh"@en
    "Kim Bang"@en
    "Kim Bảng"@en
    "Kim Son"@en
    "Kim Sơn"@en
    "Ky Anh"@en
    "Ky Lua"@en
    "Kỳ Anh"@en
    "Kỳ Lừa"@en
    "Lam Thanh"@en
    "Lam Thành"@en
    "Le Dai Hanh"@en
    "Le Ich Moc"@en
    "Lien Son Lak"@en
    "Liên Sơn Lắk"@en
    "Luong Son"@en
    "Lê Ích Mộc"@en
    "Lê Đại Hành"@en
    "Lương Sơn"@en
    "Mai Son"@en
    "Mai Sơn"@en
    "Mau Thach"@en
    "Minh Thai"@en
    "Minh Thái"@en
    "Muong Ham"@en
    "Muong La"@en
    "Muong Quang"@en
    "My Duc"@en
    "My Hao"@en
    "Mường Ham"@en
    "Mường La"@en
    "Mường Quàng"@en
    "Mậu Thạch"@en
    "Mỹ Hào"@en
    "Mỹ Đức"@en
    "Nam Dong Hung"@en
    "Nam Gianh"@en
    "Nam Hai Lang"@en
    "Nam Hoa Lu"@en
    "Nam Hoa Lư"@en
    "Nam Hải Lăng"@en
    "Nam Thai Ninh"@en
    "Nam Thuy Anh"@en
    "Nam Thái Ninh"@en
    "Nam Thụy Anh"@en
    "Nam Tien Hung"@en
    "Nam Tiên Hưng"@en
    "Nam Truc"@en
    "Nam Trực"@en
    "Nam Đông Hưng"@en
    "Nghi Loc"@en
    "Nghi Lộc"@en
    "Ngu Thien"@en
    "Nguyen Du"@en
    "Nguyễn Du"@en
    "Ngự Thiên"@en
    "Ninh Giang"@en
    "Pho Hien"@en
    "Pho Yen"@en
    "Phong Doanh"@en
    "Phu Binh"@en
    "Phu Duc"@en
    "Phu Hoa 1"@en
    "Phu Hoa 2"@en
    "Phu Vang"@en
    "Phu Yen"@en
    "Phuc Yen"@en
    "Phuong An Phong"@en
    "Phuong Cam Pha"@en
    "Phuong Chu Van An"@en
    "Phuong Dong Ha"@en
    "Phuong Dong Hai"@en
    "Phuong Duong Kinh"@en
    "Phuong Duy Tien"@en
    "Phuong Ky Lua"@en
    "Phuong Le Dai Hanh"@en
    "Phuong Le Ich Moc"@en
    "Phuong My Hao"@en
    "Phuong Nam Hoa Lu"@en
    "Phuong Pho Hien"@en
    "Phuong Pho Yen"@en
    "Phuong Phu Yen"@en
    "Phuong Phuc Yen"@en
    "Phuong Song Cong"@en
    "Phuong Tan Mai"@en
    "Phuong Thai Binh"@en
    "Phuong Thanh Vinh"@en
    "Phuong Uong Bi"@en
    "Phuong Van Xuan"@en
    "Phuong Viet Tri"@en
    "Phuong Vinh Hung"@en
    "Phuong Yen Tu"@en
    "Phú Bình"@en
    "Phú Hòa 1"@en
    "Phú Hòa 2"@en
    "Phú Vang"@en
    "Phú Yên"@en
    "Phúc Yên"@en
    "Phường An Phong"@en
    "Phường Chu Văn An"@en
    "Phường Cẩm Phả"@en
    "Phường Duy Tiên"@en
    "Phường Dương Kinh"@en
    "Phường Kỳ Lừa"@en
    "Phường Lê Ích Mộc"@en
    "Phường Lê Đại Hành"@en
    "Phường Mỹ Hào"@en
    "Phường Nam Hoa Lư"@en
    "Phường Phú Yên"@en
    "Phường Phúc Yên"@en
    "Phường Phố Hiến"@en
    "Phường Phổ Yên"@en
    "Phường Sông Công"@en
    "Phường Thành Vinh"@en
    "Phường Thái Bình"@en
    "Phường Tân Mai"@en
    "Phường Uông Bí"@en
    "Phường Vinh Hưng"@en
    "Phường Việt Trì"@en
    "Phường Vạn Xuân"@en
    "Phường Yên Tử"@en
    "Phường Đông Hà"@en
    "Phường Đông Hải"@en
    "Phố Hiến"@en
    "Phổ Yên"@en
    "Phụ Dực"@en
    "Quan Thanh"@en
    "Quan Thành"@en
    "Quang Chau"@en
    "Quang Hung"@en
    "Quang Hưng"@en
    "Que Phong"@en
    "Quynh An"@en
    "Quynh Anh"@en
    "Quynh Luu"@en
    "Quynh Nhai"@en
    "Quynh Phu"@en
    "Quynh Son"@en
    "Quảng Châu"@en
    "Quế Phong"@en
    "Quỳnh An"@en
    "Quỳnh Anh"@en
    "Quỳnh Lưu"@en
    "Quỳnh Nhai"@en
    "Quỳnh Phú"@en
    "Quỳnh Phụ"@en
    "Quỳnh Sơn"@en
    "Son Lam"@en
    "Song Cong"@en
    "Sông Công"@en
    "Sơn Lâm"@en
    "Ta Dung"@en
    "Tam Nong"@en
    "Tam Nông"@en
    "Tan Chau"@en
    "Tan Mai"@en
    "Tan Minh"@en
    "Tan Tien"@en
    "Tay Thai Ninh"@en
    "Tay Thuy Anh"@en
    "Tay Tien Hai"@en
    "Thai Binh"@en
    "Thai Ninh"@en
    "Than Khe"@en
    "Thanh Binh Tho"@en
    "Thanh Liem"@en
    "Thanh Liêm"@en
    "Thanh Vinh"@en
    "Thuy Anh"@en
    "Thành Bình Thọ"@en
    "Thành Vinh"@en
    "Thái Bình"@en
    "Thái Ninh"@en
    "Thần Khê"@en
    "Thụy Anh"@en
    "Tien Hoa"@en
    "Tien Hung"@en
    "Tien La"@en
    "Tien Lu"@en
    "Tiên Hoa"@en
    "Tiên Hưng"@en
    "Tiên La"@en
    "Tiên Lữ"@en
    "Trang Dinh"@en
    "Trieu Binh"@en
    "Trieu Phong"@en
    "Trieu Viet Vuong"@en
    "Triệu Bình"@en
    "Triệu Phong"@en
    "Triệu Việt Vương"@en
    "Truc Ninh"@en
    "Truong Luu"@en
    "Tràng Định"@en
    "Trường Lưu"@en
    "Trực Ninh"@en
    "Tue Tinh"@en
    "Tuong Duong"@en
    "Tuy An Bac"@en
    "Tuy An Bắc"@en
    "Tuệ Tĩnh"@en
    "Tà Đùng"@en
    "Tân Châu"@en
    "Tân Mai"@en
    "Tân Minh"@en
    "Tân Tiến"@en
    "Tây Thái Ninh"@en
    "Tây Thụy Anh"@en
    "Tây Tiền Hải"@en
    "Tương Dương"@en
    "Uong Bi"@en
    "Uông Bí"@en
    "Van An"@en
    "Van Du"@en
    "Van Kieu"@en
    "Van Lang"@en
    "Van Phu"@en
    "Van Thang"@en
    "Van Xuan"@en
    "Viet Tien"@en
    "Viet Tri"@en
    "Viet Yen"@en
    "Vinh Hung"@en
    "Vinh Hưng"@en
    "Vinh Loc"@en
    "Vinh Lộc"@en
    "Vinh Thuan"@en
    "Việt Tiến"@en
    "Việt Trì"@en
    "Việt Yên"@en
    "Vo Nhai"@en
    "Vu Duong"@en
    "Vân Du"@en
    "Võ Nhai"@en
    "Văn Kiều"@en
    "Văn Lãng"@en
    "Vĩnh Thuận"@en
    "Vũ Dương"@en
    "Vạn An"@en
    "Vạn Phú"@en
    "Vạn Thắng"@en
    "Vạn Xuân"@en
    "Xa A Sao"@en
    "Xa An Chau"@en
    "Xa An Khanh"@en
    "Xa An Quang"@en
    "Xa Bac Dong Hung"@en
    "Xa Bac Dong Quan"@en
    "Xa Bac Thai Ninh"@en
    "Xa Bac Thuy Anh"@en
    "Xa Bac Tien Hung"@en
    "Xa Ben Hai"@en
    "Xa Bich Hao"@en
    "Xa Binh Minh"@en
    "Xa Binh Son"@en
    "Xa Cat Ngan"@en
    "Xa Chau Ninh"@en
    "Xa Chi Minh"@en
    "Xa Con Tien"@en
    "Xa Dak Song"@en
    "Xa Dan Dien"@en
    "Xa Dong Bang"@en
    "Xa Dong Chau"@en
    "Xa Dong Loc"@en
    "Xa Dong Thai Ninh"@en
    "Xa Dong Thanh"@en
    "Xa Dong Thinh"@en
    "Xa Dong Thuy Anh"@en
    "Xa Dong Tien Hai"@en
    "Xa Dong Tien Hung"@en
    "Xa Duc Chau"@en
    "Xa Duc Lap"@en
    "Xa Duc Minh"@en
    "Xa Duong An"@en
    "Xa Giao Binh"@en
    "Xa Giao Minh"@en
    "Xa Giao Ninh"@en
    "Xa Giao Thuy"@en
    "Xa Hai Hau"@en
    "Xa Hai Hung"@en
    "Xa Hai Lang"@en
    "Xa Hai Loc"@en
    "Xa Hai Thinh"@en
    "Xa Hoa Lac"@en
    "Xa Hong Chau"@en
    "Xa Hong Phong"@en
    "Xa Hung Dao"@en
    "Xa Kim Anh"@en
    "Xa Kim Bang"@en
    "Xa Kim Son"@en
    "Xa Ky Anh"@en
    "Xa Lam Thanh"@en
    "Xa Lien Son Lak"@en
    "Xa Luong Son"@en
    "Xa Mai Son"@en
    "Xa Mau Thach"@en
    "Xa Minh Thai"@en
    "Xa Muong Ham"@en
    "Xa Muong La"@en
    "Xa Muong Quang"@en
    "Xa My Duc"@en
    "Xa Nam Dong Hung"@en
    "Xa Nam Gianh"@en
    "Xa Nam Hai Lang"@en
    "Xa Nam Thai Ninh"@en
    "Xa Nam Thuy Anh"@en
    "Xa Nam Tien Hung"@en
    "Xa Nam Truc"@en
    "Xa Nghi Loc"@en
    "Xa Ngu Thien"@en
    "Xa Nguyen Du"@en
    "Xa Ninh Giang"@en
    "Xa Phong Doanh"@en
    "Xa Phu Binh"@en
    "Xa Phu Duc"@en
    "Xa Phu Hoa 1"@en
    "Xa Phu Hoa 2"@en
    "Xa Phu Vang"@en
    "Xa Quan Thanh"@en
    "Xa Quang Chau"@en
    "Xa Quang Hung"@en
    "Xa Que Phong"@en
    "Xa Quynh An"@en
    "Xa Quynh Anh"@en
    "Xa Quynh Luu"@en
    "Xa Quynh Nhai"@en
    "Xa Quynh Phu"@en
    "Xa Quynh Son"@en
    "Xa Son Lam"@en
    "Xa Ta Dung"@en
    "Xa Tam Nong"@en
    "Xa Tan Chau"@en
    "Xa Tan Minh"@en
    "Xa Tan Tien"@en
    "Xa Tay Thai Ninh"@en
    "Xa Tay Thuy Anh"@en
    "Xa Tay Tien Hai"@en
    "Xa Thai Ninh"@en
    "Xa Than Khe"@en
    "Xa Thanh Binh Tho"@en
    "Xa Thanh Liem"@en
    "Xa Thuy Anh"@en
    "Xa Tien Hoa"@en
    "Xa Tien Hung"@en
    "Xa Tien La"@en
    "Xa Tien Lu"@en
    "Xa Trang Dinh"@en
    "Xa Trieu Binh"@en
    "Xa Trieu Phong"@en
    "Xa Trieu Viet Vuong"@en
    "Xa Truc Ninh"@en
    "Xa Truong Luu"@en
    "Xa Tue Tinh"@en
    "Xa Tuong Duong"@en
    "Xa Tuy An Bac"@en
    "Xa Van An"@en
    "Xa Van Du"@en
    "Xa Van Kieu"@en
    "Xa Van Lang"@en
    "Xa Van Phu"@en
    "Xa Van Thang"@en
    "Xa Van Xuan"@en
    "Xa Viet Tien"@en
    "Xa Viet Yen"@en
    "Xa Vinh Loc"@en
    "Xa Vinh Thuan"@en
    "Xa Vo Nhai"@en
    "Xa Vu Duong"@en
    "Xa Xuan Giang"@en
    "Xa Xuan Hung"@en
    "Xa Y Yen"@en
    "Xa Yen Xuan"@en
    "Xuan Giang"@en
    "Xuan Hung"@en
    "Xuân Giang"@en
    "Xuân Hưng"@en
    "Xã A Sào"@en
    "Xã An Châu"@en
    "Xã An Khánh"@en
    "Xã An Quang"@en
    "Xã Bình Minh"@en
    "Xã Bình Sơn"@en
    "Xã Bích Hào"@en
    "Xã Bắc Thái Ninh"@en
    "Xã Bắc Thụy Anh"@en
    "Xã Bắc Tiên Hưng"@en
    "Xã Bắc Đông Hưng"@en
    "Xã Bắc Đông Quan"@en
    "Xã Bến Hải"@en
    "Xã Châu Ninh"@en
    "Xã Chí Minh"@en
    "Xã Cát Ngạn"@en
    "Xã Cồn Tiên"@en
    "Xã Giao Bình"@en
    "Xã Giao Minh"@en
    "Xã Giao Ninh"@en
    "Xã Giao Thuỷ"@en
    "Xã Hòa Lạc"@en
    "Xã Hưng Đạo"@en
    "Xã Hải Hưng"@en
    "Xã Hải Hậu"@en
    "Xã Hải Lăng"@en
    "Xã Hải Lộc"@en
    "Xã Hải Thịnh"@en
    "Xã Hồng Châu"@en
    "Xã Hồng Phong"@en
    "Xã Kim Anh"@en
    "Xã Kim Bảng"@en
    "Xã Kim Sơn"@en
    "Xã Kỳ Anh"@en
    "Xã Lam Thành"@en
    "Xã Liên Sơn Lắk"@en
    "Xã Lương Sơn"@en
    "Xã Mai Sơn"@en
    "Xã Minh Thái"@en
    "Xã Mường Ham"@en
    "Xã Mường La"@en
    "Xã Mường Quàng"@en
    "Xã Mậu Thạch"@en
    "Xã Mỹ Đức"@en
    "Xã Nam Gianh"@en
    "Xã Nam Hải Lăng"@en
    "Xã Nam Thái Ninh"@en
    "Xã Nam Thụy Anh"@en
    "Xã Nam Tiên Hưng"@en
    "Xã Nam Trực"@en
    "Xã Nam Đông Hưng"@en
    "Xã Nghi Lộc"@en
    "Xã Nguyễn Du"@en
    "Xã Ngự Thiên"@en
    "Xã Ninh Giang"@en
    "Xã Phong Doanh"@en
    "Xã Phú Bình"@en
    "Xã Phú Hòa 1"@en
    "Xã Phú Hòa 2"@en
    "Xã Phú Vang"@en
    "Xã Phụ Dực"@en
    "Xã Quan Thành"@en
    "Xã Quang Hưng"@en
    "Xã Quảng Châu"@en
    "Xã Quế Phong"@en
    "Xã Quỳnh An"@en
    "Xã Quỳnh Anh"@en
    "Xã Quỳnh Lưu"@en
    "Xã Quỳnh Nhai"@en
    "Xã Quỳnh Phú"@en
    "Xã Quỳnh Phụ"@en
    "Xã Quỳnh Sơn"@en
    "Xã Sơn Lâm"@en
    "Xã Tam Nông"@en
    "Xã Thanh Liêm"@en
    "Xã Thành Bình Thọ"@en
    "Xã Thái Ninh"@en
    "Xã Thần Khê"@en
    "Xã Thụy Anh"@en
    "Xã Tiên Hoa"@en
    "Xã Tiên Hưng"@en
    "Xã Tiên La"@en
    "Xã Tiên Lữ"@en
    "Xã Triệu Bình"@en
    "Xã Triệu Phong"@en
    "Xã Triệu Việt Vương"@en
    "Xã Tràng Định"@en
    "Xã Trường Lưu"@en
    "Xã Trực Ninh"@en
    "Xã Tuy An Bắc"@en
    "Xã Tuệ Tĩnh"@en
    "Xã Tà Đùng"@en
    "Xã Tân Châu"@en
    "Xã Tân Minh"@en
    "Xã Tân Tiến"@en
    "Xã Tây Thái Ninh"@en
    "Xã Tây Thụy Anh"@en
    "Xã Tây Tiền Hải"@en
    "Xã Tương Dương"@en
    "Xã Vinh Lộc"@en
    "Xã Việt Tiến"@en
    "Xã Việt Yên"@en
    "Xã Vân Du"@en
    "Xã Võ Nhai"@en
    "Xã Văn Kiều"@en
    "Xã Văn Lãng"@en
    "Xã Vĩnh Thuận"@en
    "Xã Vũ Dương"@en
    "Xã Vạn An"@en
    "Xã Vạn Phú"@en
    "Xã Vạn Thắng"@en
    "Xã Vạn Xuân"@en
    "Xã Xuân Giang"@en
    "Xã Xuân Hưng"@en
    "Xã Yên Xuân"@en
    "Xã Ý Yên"@en
    "Xã Đan Điền"@en
    "Xã Đông Lộc"@en
    "Xã Đông Thành"@en
    "Xã Đông Thái Ninh"@en
    "Xã Đông Thụy Anh"@en
    "Xã Đông Tiên Hưng"@en
    "Xã Đông Tiền Hải"@en
    "Xã Đường An"@en
    "Xã Đắk Song"@en
    "Xã Đồng Bằng"@en
    "Xã Đồng Châu"@en
    "Xã Đồng Thịnh"@en
    "Xã Đức Châu"@en
    "Xã Đức Lập"@en
    "Xã Đức Minh"@en
    "Y Yen"@en
    "Yen Tu"@en
    "Yen Xuan"@en
    "Yên Tử"@en
    "Yên Xuân"@en
    "Ý Yên"@en
    "Đan Điền"@en
    "Đông Hà"@en
    "Đông Hải"@en
    "Đông Lộc"@en
    "Đông Thành"@en
    "Đông Thái Ninh"@en
    "Đông Thụy Anh"@en
    "Đông Tiên Hưng"@en
    "Đông Tiền Hải"@en
    "Đường An"@en
    "Đắk Song"@en
    "Đồng Bằng"@en
    "Đồng Châu"@en
    "Đồng Thịnh"@en
    "Đức Châu"@en
    "Đức Lập"@en
    "Đức Minh"@en
    "A Sao"@vi
    "A Sào"@vi
    "An Chau"@vi
    "An Châu"@vi
    "An Khanh"@vi
    "An Khánh"@vi
    "An Phong"@vi
    "An Quang"@vi
    "Bac Dong Hung"@vi
    "Bac Dong Quan"@vi
    "Bac Thai Ninh"@vi
    "Bac Thuy Anh"@vi
    "Bac Tien Hung"@vi
    "Ben Hai"@vi
    "Bich Hao"@vi
    "Binh Minh"@vi
    "Binh Son"@vi
    "Bình Minh"@vi
    "Bình Sơn"@vi
    "Bích Hào"@vi
    "Bắc Thái Ninh"@vi
    "Bắc Thụy Anh"@vi
    "Bắc Tiên Hưng"@vi
    "Bắc Đông Hưng"@vi
    "Bắc Đông Quan"@vi
    "Bến Hải"@vi
    "Cam Pha"@vi
    "Cat Ngan"@vi
    "Chau Ninh"@vi
    "Chi Minh"@vi
    "Chu Van An"@vi
    "Chu Văn An"@vi
    "Châu Ninh"@vi
    "Chí Minh"@vi
    "Con Tien"@vi
    "Cát Ngạn"@vi
    "Cẩm Phả"@vi
    "Cồn Tiên"@vi
    "Dak Song"@vi
    "Dan Dien"@vi
    "Dong Bang"@vi
    "Dong Chau"@vi
    "Dong Ha"@vi
    "Dong Hai"@vi
    "Dong Loc"@vi
    "Dong Thai Ninh"@vi
    "Dong Thanh"@vi
    "Dong Thinh"@vi
    "Dong Thuy Anh"@vi
    "Dong Tien Hai"@vi
    "Dong Tien Hung"@vi
    "Duc Chau"@vi
    "Duc Lap"@vi
    "Duc Minh"@vi
    "Duong An"@vi
    "Duong Kinh"@vi
    "Duy Tien"@vi
    "Duy Tiên"@vi
    "Dương Kinh"@vi
    "Giao Binh"@vi
    "Giao Bình"@vi
    "Giao Minh"@vi
    "Giao Ninh"@vi
    "Giao Thuy"@vi
    "Giao Thuỷ"@vi
    "Hai Hau"@vi
    "Hai Hung"@vi
    "Hai Lang"@vi
    "Hai Loc"@vi
    "Hai Thinh"@vi
    "Hoa Lac"@vi
    "Hong Chau"@vi
    "Hong Phong"@vi
    "Hung Dao"@vi
    "Hòa Lạc"@vi
    "Hưng Đạo"@vi
    "Hải Hưng"@vi
    "Hải Hậu"@vi
    "Hải Lăng"@vi
    "Hải Lộc"@vi
    "Hải Thịnh"@vi
    "Hồng Châu"@vi
    "Hồng Phong"@vi
    "Kim Anh"@vi
    "Kim Bang"@vi
    "Kim Bảng"@vi
    "Kim Son"@vi
    "Kim Sơn"@vi
    "Ky Anh"@vi
    "Ky Lua"@vi
    "Kỳ Anh"@vi
    "Kỳ Lừa"@vi
    "Lam Thanh"@vi
    "Lam Thành"@vi
    "Le Dai Hanh"@vi
    "Le Ich Moc"@vi
    "Lien Son Lak"@vi
    "Liên Sơn Lắk"@vi
    "Luong Son"@vi
    "Lê Ích Mộc"@vi
    "Lê Đại Hành"@vi
    "Lương Sơn"@vi
    "Mai Son"@vi
    "Mai Sơn"@vi
    "Mau Thach"@vi
    "Minh Thai"@vi
    "Minh Thái"@vi
    "Muong Ham"@vi
    "Muong La"@vi
    "Muong Quang"@vi
    "My Duc"@vi
    "My Hao"@vi
    "Mường Ham"@vi
    "Mường La"@vi
    "Mường Quàng"@vi
    "Mậu Thạch"@vi
    "Mỹ Hào"@vi
    "Mỹ Đức"@vi
    "Nam Dong Hung"@vi
    "Nam Gianh"@vi
    "Nam Hai Lang"@vi
    "Nam Hoa Lu"@vi
    "Nam Hoa Lư"@vi
    "Nam Hải Lăng"@vi
    "Nam Thai Ninh"@vi
    "Nam Thuy Anh"@vi
    "Nam Thái Ninh"@vi
    "Nam Thụy Anh"@vi
    "Nam Tien Hung"@vi
    "Nam Tiên Hưng"@vi
    "Nam Truc"@vi
    "Nam Trực"@vi
    "Nam Đông Hưng"@vi
    "Nghi Loc"@vi
    "Nghi Lộc"@vi
    "Ngu Thien"@vi
    "Nguyen Du"@vi
    "Nguyễn Du"@vi
    "Ngự Thiên"@vi
    "Ninh Giang"@vi
    "Pho Hien"@vi
    "Pho Yen"@vi
    "Phong Doanh"@vi
    "Phu Binh"@vi
    "Phu Duc"@vi
    "Phu Hoa 1"@vi
    "Phu Hoa 2"@vi
    "Phu Vang"@vi
    "Phu Yen"@vi
    "Phuc Yen"@vi
    "Phuong An Phong"@vi
    "Phuong Cam Pha"@vi
    "Phuong Chu Van An"@vi
    "Phuong Dong Ha"@vi
    "Phuong Dong Hai"@vi
    "Phuong Duong Kinh"@vi
    "Phuong Duy Tien"@vi
    "Phuong Ky Lua"@vi
    "Phuong Le Dai Hanh"@vi
    "Phuong Le Ich Moc"@vi
    "Phuong My Hao"@vi
    "Phuong Nam Hoa Lu"@vi
    "Phuong Pho Hien"@vi
    "Phuong Pho Yen"@vi
    "Phuong Phu Yen"@vi
    "Phuong Phuc Yen"@vi
    "Phuong Song Cong"@vi
    "Phuong Tan Mai"@vi
    "Phuong Thai Binh"@vi
    "Phuong Thanh Vinh"@vi
    "Phuong Uong Bi"@vi
    "Phuong Van Xuan"@vi
    "Phuong Viet Tri"@vi
    "Phuong Vinh Hung"@vi
    "Phuong Yen Tu"@vi
    "Phú Bình"@vi
    "Phú Hòa 1"@vi
    "Phú Hòa 2"@vi
    "Phú Vang"@vi
    "Phú Yên"@vi
    "Phúc Yên"@vi
    "Phường An Phong"@vi
    "Phường Chu Văn An"@vi
    "Phường Cẩm Phả"@vi
    "Phường Duy Tiên"@vi
    "Phường Dương Kinh"@vi
    "Phường Kỳ Lừa"@vi
    "Phường Lê Ích Mộc"@vi
    "Phường Lê Đại Hành"@vi
    "Phường Mỹ Hào"@vi
    "Phường Nam Hoa Lư"@vi
    "Phường Phú Yên"@vi
    "Phường Phúc Yên"@vi
    "Phường Phố Hiến"@vi
    "Phường Phổ Yên"@vi
    "Phường Sông Công"@vi
    "Phường Thành Vinh"@vi
    "Phường Thái Bình"@vi
    "Phường Tân Mai"@vi
    "Phường Uông Bí"@vi
    "Phường Vinh Hưng"@vi
    "Phường Việt Trì"@vi
    "Phường Vạn Xuân"@vi
    "Phường Yên Tử"@vi
    "Phường Đông Hà"@vi
    "Phường Đông Hải"@vi
    "Phố Hiến"@vi
    "Phổ Yên"@vi
    "Phụ Dực"@vi
    "Quan Thanh"@vi
    "Quan Thành"@vi
    "Quang Chau"@vi
    "Quang Hung"@vi
    "Quang Hưng"@vi
    "Que Phong"@vi
    "Quynh An"@vi
    "Quynh Anh"@vi
    "Quynh Luu"@vi
    "Quynh Nhai"@vi
    "Quynh Phu"@vi
    "Quynh Son"@vi
    "Quảng Châu"@vi
    "Quế Phong"@vi
    "Quỳnh An"@vi
    "Quỳnh Anh"@vi
    "Quỳnh Lưu"@vi
    "Quỳnh Nhai"@vi
    "Quỳnh Phú"@vi
    "Quỳnh Phụ"@vi
    "Quỳnh Sơn"@vi
    "Son Lam"@vi
    "Song Cong"@vi
    "Sông Công"@vi
    "Sơn Lâm"@vi
    "Ta Dung"@vi
    "Tam Nong"@vi
    "Tam Nông"@vi
    "Tan Chau"@vi
    "Tan Mai"@vi
    "Tan Minh"@vi
    "Tan Tien"@vi
    "Tay Thai Ninh"@vi
    "Tay Thuy Anh"@vi
    "Tay Tien Hai"@vi
    "Thai Binh"@vi
    "Thai Ninh"@vi
    "Than Khe"@vi
    "Thanh Binh Tho"@vi
    "Thanh Liem"@vi
    "Thanh Liêm"@vi
    "Thanh Vinh"@vi
    "Thuy Anh"@vi
    "Thành Bình Thọ"@vi
    "Thành Vinh"@vi
    "Thái Bình"@vi
    "Thái Ninh"@vi
    "Thần Khê"@vi
    "Thụy Anh"@vi
    "Tien Hoa"@vi
    "Tien Hung"@vi
    "Tien La"@vi
    "Tien Lu"@vi
    "Tiên Hoa"@vi
    "Tiên Hưng"@vi
    "Tiên La"@vi
    "Tiên Lữ"@vi
    "Trang Dinh"@vi
    "Trieu Binh"@vi
    "Trieu Phong"@vi
    "Trieu Viet Vuong"@vi
    "Triệu Bình"@vi
    "Triệu Phong"@vi
    "Triệu Việt Vương"@vi
    "Truc Ninh"@vi
    "Truong Luu"@vi
    "Tràng Định"@vi
    "Trường Lưu"@vi
    "Trực Ninh"@vi
    "Tue Tinh"@vi
    "Tuong Duong"@vi
    "Tuy An Bac"@vi
    "Tuy An Bắc"@vi
    "Tuệ Tĩnh"@vi
    "Tà Đùng"@vi
    "Tân Châu"@vi
    "Tân Mai"@vi
    "Tân Minh"@vi
    "Tân Tiến"@vi
    "Tây Thái Ninh"@vi
    "Tây Thụy Anh"@vi
    "Tây Tiền Hải"@vi
    "Tương Dương"@vi
    "Uong Bi"@vi
    "Uông Bí"@vi
    "Van An"@vi
    "Van Du"@vi
    "Van Kieu"@vi
    "Van Lang"@vi
    "Van Phu"@vi
    "Van Thang"@vi
    "Van Xuan"@vi
    "Viet Tien"@vi
    "Viet Tri"@vi
    "Viet Yen"@vi
    "Vinh Hung"@vi
    "Vinh Hưng"@vi
    "Vinh Loc"@vi
    "Vinh Lộc"@vi
    "Vinh Thuan"@vi
    "Việt Tiến"@vi
    "Việt Trì"@vi
    "Việt Yên"@vi
    "Vo Nhai"@vi
    "Vu Duong"@vi
    "Vân Du"@vi
    "Võ Nhai"@vi
    "Văn Kiều"@vi
    "Văn Lãng"@vi
    "Vĩnh Thuận"@vi
    "Vũ Dương"@vi
    "Vạn An"@vi
    "Vạn Phú"@vi
    "Vạn Thắng"@vi
    "Vạn Xuân"@vi
    "Xa A Sao"@vi
    "Xa An Chau"@vi
    "Xa An Khanh"@vi
    "Xa An Quang"@vi
    "Xa Bac Dong Hung"@vi
    "Xa Bac Dong Quan"@vi
    "Xa Bac Thai Ninh"@vi
    "Xa Bac Thuy Anh"@vi
    "Xa Bac Tien Hung"@vi
    "Xa Ben Hai"@vi
    "Xa Bich Hao"@vi
    "Xa Binh Minh"@vi
    "Xa Binh Son"@vi
    "Xa Cat Ngan"@vi
    "Xa Chau Ninh"@vi
    "Xa Chi Minh"@vi
    "Xa Con Tien"@vi
    "Xa Dak Song"@vi
    "Xa Dan Dien"@vi
    "Xa Dong Bang"@vi
    "Xa Dong Chau"@vi
    "Xa Dong Loc"@vi
    "Xa Dong Thai Ninh"@vi
    "Xa Dong Thanh"@vi
    "Xa Dong Thinh"@vi
    "Xa Dong Thuy Anh"@vi
    "Xa Dong Tien Hai"@vi
    "Xa Dong Tien Hung"@vi
    "Xa Duc Chau"@vi
    "Xa Duc Lap"@vi
    "Xa Duc Minh"@vi
    "Xa Duong An"@vi
    "Xa Giao Binh"@vi
    "Xa Giao Minh"@vi
    "Xa Giao Ninh"@vi
    "Xa Giao Thuy"@vi
    "Xa Hai Hau"@vi
    "Xa Hai Hung"@vi
    "Xa Hai Lang"@vi
    "Xa Hai Loc"@vi
    "Xa Hai Thinh"@vi
    "Xa Hoa Lac"@vi
    "Xa Hong Chau"@vi
    "Xa Hong Phong"@vi
    "Xa Hung Dao"@vi
    "Xa Kim Anh"@vi
    "Xa Kim Bang"@vi
    "Xa Kim Son"@vi
    "Xa Ky Anh"@vi
    "Xa Lam Thanh"@vi
    "Xa Lien Son Lak"@vi
    "Xa Luong Son"@vi
    "Xa Mai Son"@vi
    "Xa Mau Thach"@vi
    "Xa Minh Thai"@vi
    "Xa Muong Ham"@vi
    "Xa Muong La"@vi
    "Xa Muong Quang"@vi
    "Xa My Duc"@vi
    "Xa Nam Dong Hung"@vi
    "Xa Nam Gianh"@vi
    "Xa Nam Hai Lang"@vi
    "Xa Nam Thai Ninh"@vi
    "Xa Nam Thuy Anh"@vi
    "Xa Nam Tien Hung"@vi
    "Xa Nam Truc"@vi
    "Xa Nghi Loc"@vi
    "Xa Ngu Thien"@vi
    "Xa Nguyen Du"@vi
    "Xa Ninh Giang"@vi
    "Xa Phong Doanh"@vi
    "Xa Phu Binh"@vi
    "Xa Phu Duc"@vi
    "Xa Phu Hoa 1"@vi
    "Xa Phu Hoa 2"@vi
    "Xa Phu Vang"@vi
    "Xa Quan Thanh"@vi
    "Xa Quang Chau"@vi
    "Xa Quang Hung"@vi
    "Xa Que Phong"@vi
    "Xa Quynh An"@vi
    "Xa Quynh Anh"@vi
    "Xa Quynh Luu"@vi
    "Xa Quynh Nhai"@vi
    "Xa Quynh Phu"@vi
    "Xa Quynh Son"@vi
    "Xa Son Lam"@vi
    "Xa Ta Dung"@vi
    "Xa Tam Nong"@vi
    "Xa Tan Chau"@vi
    "Xa Tan Minh"@vi
    "Xa Tan Tien"@vi
    "Xa Tay Thai Ninh"@vi
    "Xa Tay Thuy Anh"@vi
    "Xa Tay Tien Hai"@vi
    "Xa Thai Ninh"@vi
    "Xa Than Khe"@vi
    "Xa Thanh Binh Tho"@vi
    "Xa Thanh Liem"@vi
    "Xa Thuy Anh"@vi
    "Xa Tien Hoa"@vi
    "Xa Tien Hung"@vi
    "Xa Tien La"@vi
    "Xa Tien Lu"@vi
    "Xa Trang Dinh"@vi
    "Xa Trieu Binh"@vi
    "Xa Trieu Phong"@vi
    "Xa Trieu Viet Vuong"@vi
    "Xa Truc Ninh"@vi
    "Xa Truong Luu"@vi
    "Xa Tue Tinh"@vi
    "Xa Tuong Duong"@vi
    "Xa Tuy An Bac"@vi
    "Xa Van An"@vi
    "Xa Van Du"@vi
    "Xa Van Kieu"@vi
    "Xa Van Lang"@vi
    "Xa Van Phu"@vi
    "Xa Van Thang"@vi
    "Xa Van Xuan"@vi
    "Xa Viet Tien"@vi
    "Xa Viet Yen"@vi
    "Xa Vinh Loc"@vi
    "Xa Vinh Thuan"@vi
    "Xa Vo Nhai"@vi
    "Xa Vu Duong"@vi
    "Xa Xuan Giang"@vi
    "Xa Xuan Hung"@vi
    "Xa Y Yen"@vi
    "Xa Yen Xuan"@vi
    "Xuan Giang"@vi
    "Xuan Hung"@vi
    "Xuân Giang"@vi
    "Xuân Hưng"@vi
    "Xã A Sào"@vi
    "Xã An Châu"@vi
    "Xã An Khánh"@vi
    "Xã An Quang"@vi
    "Xã Bình Minh"@vi
    "Xã Bình Sơn"@vi
    "Xã Bích Hào"@vi
    "Xã Bắc Thái Ninh"@vi
    "Xã Bắc Thụy Anh"@vi
    "Xã Bắc Tiên Hưng"@vi
    "Xã Bắc Đông Hưng"@vi
    "Xã Bắc Đông Quan"@vi
    "Xã Bến Hải"@vi
    "Xã Châu Ninh"@vi
    "Xã Chí Minh"@vi
    "Xã Cát Ngạn"@vi
    "Xã Cồn Tiên"@vi
    "Xã Giao Bình"@vi
    "Xã Giao Minh"@vi
    "Xã Giao Ninh"@vi
    "Xã Giao Thuỷ"@vi
    "Xã Hòa Lạc"@vi
    "Xã Hưng Đạo"@vi
    "Xã Hải Hưng"@vi
    "Xã Hải Hậu"@vi
    "Xã Hải Lăng"@vi
    "Xã Hải Lộc"@vi
    "Xã Hải Thịnh"@vi
    "Xã Hồng Châu"@vi
    "Xã Hồng Phong"@vi
    "Xã Kim Anh"@vi
    "Xã Kim Bảng"@vi
    "Xã Kim Sơn"@vi
    "Xã Kỳ Anh"@vi
    "Xã Lam Thành"@vi
    "Xã Liên Sơn Lắk"@vi
    "Xã Lương Sơn"@vi
    "Xã Mai Sơn"@vi
    "Xã Minh Thái"@vi
    "Xã Mường Ham"@vi
    "Xã Mường La"@vi
    "Xã Mường Quàng"@vi
    "Xã Mậu Thạch"@vi
    "Xã Mỹ Đức"@vi
    "Xã Nam Gianh"@vi
    "Xã Nam Hải Lăng"@vi
    "Xã Nam Thái Ninh"@vi
    "Xã Nam Thụy Anh"@vi
    "Xã Nam Tiên Hưng"@vi
    "Xã Nam Trực"@vi
    "Xã Nam Đông Hưng"@vi
    "Xã Nghi Lộc"@vi
    "Xã Nguyễn Du"@vi
    "Xã Ngự Thiên"@vi
    "Xã Ninh Giang"@vi
    "Xã Phong Doanh"@vi
    "Xã Phú Bình"@vi
    "Xã Phú Hòa 1"@vi
    "Xã Phú Hòa 2"@vi
    "Xã Phú Vang"@vi
    "Xã Phụ Dực"@vi
    "Xã Quan Thành"@vi
    "Xã Quang Hưng"@vi
    "Xã Quảng Châu"@vi
    "Xã Quế Phong"@vi
    "Xã Quỳnh An"@vi
    "Xã Quỳnh Anh"@vi
    "Xã Quỳnh Lưu"@vi
    "Xã Quỳnh Nhai"@vi
    "Xã Quỳnh Phú"@vi
    "Xã Quỳnh Phụ"@vi
    "Xã Quỳnh Sơn"@vi
    "Xã Sơn Lâm"@vi
    "Xã Tam Nông"@vi
    "Xã Thanh Liêm"@vi
    "Xã Thành Bình Thọ"@vi
    "Xã Thái Ninh"@vi
    "Xã Thần Khê"@vi
    "Xã Thụy Anh"@vi
    "Xã Tiên Hoa"@vi
    "Xã Tiên Hưng"@vi
    "Xã Tiên La"@vi
    "Xã Tiên Lữ"@vi
    "Xã Triệu Bình"@vi
    "Xã Triệu Phong"@vi
    "Xã Triệu Việt Vương"@vi
    "Xã Tràng Định"@vi
    "Xã Trường Lưu"@vi
    "Xã Trực Ninh"@vi
    "Xã Tuy An Bắc"@vi
    "Xã Tuệ Tĩnh"@vi
    "Xã Tà Đùng"@vi
    "Xã Tân Châu"@vi
    "Xã Tân Minh"@vi
    "Xã Tân Tiến"@vi
    "Xã Tây Thái Ninh"@vi
    "Xã Tây Thụy Anh"@vi
    "Xã Tây Tiền Hải"@vi
    "Xã Tương Dương"@vi
    "Xã Vinh Lộc"@vi
    "Xã Việt Tiến"@vi
    "Xã Việt Yên"@vi
    "Xã Vân Du"@vi
    "Xã Võ Nhai"@vi
    "Xã Văn Kiều"@vi
    "Xã Văn Lãng"@vi
    "Xã Vĩnh Thuận"@vi
    "Xã Vũ Dương"@vi
    "Xã Vạn An"@vi
    "Xã Vạn Phú"@vi
    "Xã Vạn Thắng"@vi
    "Xã Vạn Xuân"@vi
    "Xã Xuân Giang"@vi
    "Xã Xuân Hưng"@vi
    "Xã Yên Xuân"@vi
    "Xã Ý Yên"@vi
    "Xã Đan Điền"@vi
    "Xã Đông Lộc"@vi
    "Xã Đông Thành"@vi
    "Xã Đông Thái Ninh"@vi
    "Xã Đông Thụy Anh"@vi
    "Xã Đông Tiên Hưng"@vi
    "Xã Đông Tiền Hải"@vi
    "Xã Đường An"@vi
    "Xã Đắk Song"@vi
    "Xã Đồng Bằng"@vi
    "Xã Đồng Châu"@vi
    "Xã Đồng Thịnh"@vi
    "Xã Đức Châu"@vi
    "Xã Đức Lập"@vi
    "Xã Đức Minh"@vi
    "Y Yen"@vi
    "Yen Tu"@vi
    "Yen Xuan"@vi
    "Yên Tử"@vi
    "Yên Xuân"@vi
    "Ý Yên"@vi
    "Đan Điền"@vi
    "Đông Hà"@vi
    "Đông Hải"@vi
    "Đông Lộc"@vi
    "Đông Thành"@vi
    "Đông Thái Ninh"@vi
    "Đông Thụy Anh"@vi
    "Đông Tiên Hưng"@vi
    "Đông Tiền Hải"@vi
    "Đường An"@vi
    "Đắk Song"@vi
    "Đồng Bằng"@vi
    "Đồng Châu"@vi
    "Đồng Thịnh"@vi
    "Đức Châu"@vi
    "Đức Lập"@vi
    "Đức Minh"@vi
    }
    ?item skos:altLabel ?matchedTerm .
    BIND("alias" AS ?matchKind)
  }
}
ORDER BY ?item ?matchedTerm ?matchKind
